package city

import "github.com/woningfinder/woningfinder/internal/entity"

// https://nl.wikipedia.org/wiki/Wijken_en_buurten_in_Enschede
var Enschede = entity.City{
	Name: "Enschede",
	District: []entity.CityDistrict{
		{Name: "City (Oude Markt)"},
		{Name: "Lasonder, Zeggelt"},
		{Name: "De Laares"},
		{Name: "De Bothoven"},
		{Name: "Hogeland"},
		{Name: "Getfert"},
		{Name: "Veldkamp"},
		{Name: "Stadsweide"},
		{Name: "Boddenkamp"},
		{Name: "Velve-Lindenhof"},
		{Name: "Wooldrik"},
		{Name: "Varvik-Diekman"},
		{Name: "Sleutelkamp"},
		{Name: "De Leuriks"},
		{Name: "Cromhoffsbleek"},
		{Name: "Boswinkel"},
		{Name: "Pathmos"},
		{Name: "Stevenfenne"},
		{Name: "Stadsveld"},
		{Name: "Elferink-Heuwkamp"},
		{Name: "'t Zwering"},
		{Name: "Ruwenbos"},
		{Name: "Tubantia-Toekomst"},
		{Name: "Twekkelerveld"},
		{Name: "Roessingh"},
		{Name: "Bolhaar"},
		{Name: "Roombeek-Roomveldje"},
		{Name: "Mekkelholt"},
		{Name: "Deppenbroek"},
		{Name: "Voortman-Amelink"},
		{Name: "Drienerveld-U.T."},
		{Name: "Schreurserve"},
		{Name: "Ribbelt"},
		{Name: "Stokhorst"},
		{Name: "Stroinkslanden"},
		{Name: "Helmerhoek"},
		{Name: "Glanerveld (Glanerbrug)"},
		{Name: "Bentveld-Bultserve (Glanerbrug)"},
		{Name: "Schipholt-Glanermaten (Glanerbrug)"},
		{Name: "Eekmaat (Glanerbrug)"},
		{Name: "Oikos (Glanerbrug)"},
		{Name: "Dolphia (Glanerbrug)"},
	},
}
