package city

import (
	"strings"
	"time"
)

// CityTable defines the city name and it's corresponding struct
var CityTable = map[string]City{
	Aalten.Name:                  Aalten,
	Dinxperlo.Name:               Dinxperlo,
	Bredevoort.Name:              Bredevoort,
	Neede.Name:                   Neede,
	Borne.Name:                   Borne,
	Bussum.Name:                  Bussum,
	Wehl.Name:                    Wehl,
	Enschede.Name:                Enschede,
	Haaksbergen.Name:             Haaksbergen,
	Hengelo.Name:                 Hengelo,
	Losser.Name:                  Losser,
	Overdinkel.Name:              Overdinkel,
	DeLutte.Name:                 DeLutte,
	Groenlo.Name:                 Groenlo,
	Ulft.Name:                    Ulft,
	Winterswijk.Name:             Winterswijk,
	Zwolle.Name:                  Zwolle,
	Almelo.Name:                  Almelo,
	Hertme.Name:                  Hertme,
	Apeldoorn.Name:               Apeldoorn,
	Heerenberg.Name:              Heerenberg,
	Zenderen.Name:                Zenderen,
	Utrecht.Name:                 Utrecht,
	Zeist.Name:                   Zeist,
	Bilthoven.Name:               Bilthoven,
	Bunnik.Name:                  Bunnik,
	Nieuwegein.Name:              Nieuwegein,
	Maarssen.Name:                Maarssen,
	WijkBijDuurstede.Name:        WijkBijDuurstede,
	DenDoler.Name:                DenDoler,
	Maartensdijk.Name:            Maartensdijk,
	Baambrugge.Name:              Baambrugge,
	Wilnis.Name:                  Wilnis,
	Woerden.Name:                 Woerden,
	Vianen.Name:                  Vianen,
	DeMeern.Name:                 DeMeern,
	Papekop.Name:                 Papekop,
	Breukelen.Name:               Breukelen,
	DeBilt.Name:                  DeBilt,
	IJsselstein.Name:             IJsselstein,
	Vleuten.Name:                 Vleuten,
	DriebergenRijsenburg.Name:    DriebergenRijsenburg,
	Mijdrecht.Name:               Mijdrecht,
	Linschoten.Name:              Linschoten,
	Odijk.Name:                   Odijk,
	Doorn.Name:                   Doorn,
	Oudewater.Name:               Oudewater,
	Vreeland.Name:                Vreeland,
	Denekamp.Name:                Denekamp,
	Ootmarsum.Name:               Ootmarsum,
	Vriezenveen.Name:             Vriezenveen,
	Houten.Name:                  Houten,
	Vinkeveen.Name:               Vinkeveen,
	Harmelen.Name:                Harmelen,
	Amsterdam.Name:               Amsterdam,
	Amstelveen.Name:              Amstelveen,
	Aalsmeer.Name:                Aalsmeer,
	Diemen.Name:                  Diemen,
	Zaandam.Name:                 Zaandam,
	Hoofddorp.Name:               Hoofddorp,
	Krommenie.Name:               Krommenie,
	Kudelstaart.Name:             Kudelstaart,
	Landsmeer.Name:               Landsmeer,
	Marken.Name:                  Marken,
	NieuwVennep.Name:             NieuwVennep,
	Oostzaan.Name:                Oostzaan,
	OuderkerkAanDeAmstel.Name:    OuderkerkAanDeAmstel,
	Purmerend.Name:               Purmerend,
	Uithoorn.Name:                Uithoorn,
	Vijfhuizen.Name:              Vijfhuizen,
	Wormer.Name:                  Wormer,
	Zwanenburg.Name:              Zwanenburg,
	Lopik.Name:                   Lopik,
	Langbroek.Name:               Langbroek,
	Zuidoostbeemster.Name:        Zuidoostbeemster,
	Zaandijk.Name:                Zaandijk,
	Badhoevedorp.Name:            Badhoevedorp,
	DeKwakel.Name:                DeKwakel,
	Lisserbroek.Name:             Lisserbroek,
	Purmerland.Name:              Purmerland,
	Kockengen.Name:               Kockengen,
	Polsbroek.Name:               Polsbroek,
	Hagestein.Name:               Hagestein,
	Kampen.Name:                  Kampen,
	IJsselmuiden.Name:            IJsselmuiden,
	Wanneperveen.Name:            Wanneperveen,
	Vollenhove.Name:              Vollenhove,
	KoogaandeZaan.Name:           KoogaandeZaan,
	Leersum.Name:                 Leersum,
	Abcoude.Name:                 Abcoude,
	Maarn.Name:                   Maarn,
	Leerdam.Name:                 Leerdam,
	Kamerik.Name:                 Kamerik,
	Assendelft.Name:              Assendelft,
	Wormerveer.Name:              Wormerveer,
	Wijthmen.Name:                Wijthmen,
	Jisp.Name:                    Jisp,
	Rijsenhout.Name:              Rijsenhout,
	Willemsoord.Name:             Willemsoord,
	Zegveld.Name:                 Zegveld,
	Middenbeemster.Name:          Middenbeemster,
	Monnickendam.Name:            Monnickendam,
	Westzaan.Name:                Westzaan,
	Beinsdorp.Name:               Beinsdorp,
	Cothen.Name:                  Cothen,
	Giethoorn.Name:               Giethoorn,
	Cruquius.Name:                Cruquius,
	Aadorp.Name:                  Aadorp,
	Bornerbroek.Name:             Bornerbroek,
	Wierden.Name:                 Wierden,
	Cruquius.Name:                Cruquius,
	Hertogenbosch.Name:           Hertogenbosch,
	Maastricht.Name:              Maastricht,
	Heerenveen.Name:              Heerenveen,
	Deventer.Name:                Deventer,
	Terborg.Name:                 Terborg,
	Haaften.Name:                 Haaften,
	Loosdrecht.Name:              Loosdrecht,
	Deurne.Name:                  Deurne,
	Soest.Name:                   Soest,
	OudBeijerland.Name:           OudBeijerland,
	Uden.Name:                    Uden,
	Doetinchem.Name:              Doetinchem,
	HendrikIdoAmbacht.Name:       HendrikIdoAmbacht,
	CapelleAanDenIJssel.Name:     CapelleAanDenIJssel,
	Kortenhoef.Name:              Kortenhoef,
	Hoogeveen.Name:               Hoogeveen,
	Voorhout.Name:                Voorhout,
	Voorburg.Name:                Voorburg,
	Amersfoort.Name:              Amersfoort,
	Dieren.Name:                  Dieren,
	Ede.Name:                     Ede,
	Breda.Name:                   Breda,
	Arnhem.Name:                  Arnhem,
	Hoogvliet.Name:               Hoogvliet,
	Oss.Name:                     Oss,
	Heemstede.Name:               Heemstede,
	Echt.Name:                    Echt,
	Delft.Name:                   Delft,
	Terneuzen.Name:               Terneuzen,
	Roosendaal.Name:              Roosendaal,
	Harderwijk.Name:              Harderwijk,
	Hardenberg.Name:              Hardenberg,
	Zoetermeer.Name:              Zoetermeer,
	Winschoten.Name:              Winschoten,
	Hilversum.Name:               Hilversum,
	Groesbeek.Name:               Groesbeek,
	Naaldwijk.Name:               Naaldwijk,
	Heerlen.Name:                 Heerlen,
	Sliedrecht.Name:              Sliedrecht,
	Leerbroek.Name:               Leerbroek,
	Groningen.Name:               Groningen,
	Kaatsheuvel.Name:             Kaatsheuvel,
	Prinsenbeek.Name:             Prinsenbeek,
	Eindhoven.Name:               Eindhoven,
	Papendrecht.Name:             Papendrecht,
	Oegstgeest.Name:              Oegstgeest,
	Goes.Name:                    Goes,
	DenHaag.Name:                 DenHaag,
	Roermond.Name:                Roermond,
	Leiden.Name:                  Leiden,
	Tilburg.Name:                 Tilburg,
	Ermelo.Name:                  Ermelo,
	Vlissingen.Name:              Vlissingen,
	Gorinchem.Name:               Gorinchem,
	Waalwijk.Name:                Waalwijk,
	Rotterdam.Name:               Rotterdam,
	Oldenzaal.Name:               Oldenzaal,
	Schiedam.Name:                Schiedam,
	Alkmaar.Name:                 Alkmaar,
	Blaricum.Name:                Blaricum,
	Best.Name:                    Best,
	Heerhugowaard.Name:           Heerhugowaard,
	Borculo.Name:                 Borculo,
	Hulst.Name:                   Hulst,
	Voorst.Name:                  Voorst,
	Haarlem.Name:                 Haarlem,
	Wijchen.Name:                 Wijchen,
	Almere.Name:                  Almere,
	Dordrecht.Name:               Dordrecht,
	Alblasserdam.Name:            Alblasserdam,
	Zwijndrecht.Name:             Zwijndrecht,
	Achterveld.Name:              Achterveld,
	Nijkerk.Name:                 Nijkerk,
	Nijkerkerveen.Name:           Nijkerkerveen,
	Soesterberg.Name:             Soesterberg,
	Beverwijk.Name:               Beverwijk,
	Bant.Name:                    Bant,
	Emmeloord.Name:               Emmeloord,
	Nagele.Name:                  Nagele,
	Bodegraven.Name:              Bodegraven,
	Gouda.Name:                   Gouda,
	Waddinxveen.Name:             Waddinxveen,
	Zevenhuizen.Name:             Zevenhuizen,
	Eenrum.Name:                  Eenrum,
	Ezinge.Name:                  Ezinge,
	Kloosterburen.Name:           Kloosterburen,
	Winsum.Name:                  Winsum,
	Graveland.Name:               Graveland,
	Ankeveen.Name:                Ankeveen,
	Huizen.Name:                  Huizen,
	Muiden.Name:                  Muiden,
	Barneveld.Name:               Barneveld,
	Bennekom.Name:                Bennekom,
	Elst.Name:                    Elst,
	Lunteren.Name:                Lunteren,
	Rhenen.Name:                  Rhenen,
	Scherpenzeel.Name:            Scherpenzeel,
	Terschuur.Name:               Terschuur,
	Veenendaal.Name:              Veenendaal,
	Wageningen.Name:              Wageningen,
	Wekerom.Name:                 Wekerom,
	Arkel.Name:                   Arkel,
	BenedenLeeuwen.Name:          BenedenLeeuwen,
	Culemborg.Name:               Culemborg,
	Est.Name:                     Est,
	Geldermalsen.Name:            Geldermalsen,
	HardinxveldGiessendam.Name:   HardinxveldGiessendam,
	Hedel.Name:                   Hedel,
	Maurik.Name:                  Maurik,
	Meerkerk.Name:                Meerkerk,
	Opheusden.Name:               Opheusden,
	Rossum.Name:                  Rossum,
	Tiel.Name:                    Tiel,
	Veen.Name:                    Veen,
	WijkEnAalburg.Name:           WijkEnAalburg,
	Zaltbommel.Name:              Zaltbommel,
	Asperen.Name:                 Asperen,
	BunschotenSpakenburg.Name:    BunschotenSpakenburg,
	Baarn.Name:                   Baarn,
	Woudenberg.Name:              Woudenberg,
	Eemnes.Name:                  Eemnes,
	Hoogland.Name:                Hoogland,
	IJmuiden.Name:                IJmuiden,
	Velserbroek.Name:             Velserbroek,
	HuisTerHeide.Name:            HuisTerHeide,
	NieuwerkerkAanDenIJssel.Name: NieuwerkerkAanDenIJssel,
	Herwijnen.Name:               Herwijnen,
	Hernen.Name:                  Hernen,
	Werkendam.Name:               Werkendam,
	Ingen.Name:                   Ingen,
	Sleeuwijk.Name:               Sleeuwijk,
	Nieuwendijk.Name:             Nieuwendijk,
	Woudrichem.Name:              Woudrichem,
	Eethen.Name:                  Eethen,
	Valkenswaard.Name:            Valkenswaard,
	Hoevelaken.Name:              Hoevelaken,
	Zandvoort.Name:               Zandvoort,
	Hank.Name:                    Hank,
	Meteren.Name:                 Meteren,
	Barendrecht.Name:             Barendrecht,
	Weesp.Name:                   Weesp,
	Blokzijl.Name:                Blokzijl,
	Hasselt.Name:                 Hasselt,
	Kerkdriel.Name:               Kerkdriel,
	Waverveen.Name:               Waverveen,
	TenBoer.Name:                 TenBoer,
	Naarden.Name:                 Naarden,
	Loppersum.Name:               Loppersum,
	Middelstum.Name:              Middelstum,
	Zwartsluis.Name:              Zwartsluis,
	Oisterwijk.Name:              Oisterwijk,
	AlphenAanDenRijn.Name:        AlphenAanDenRijn,
	Lelystad.Name:                Lelystad,
	Zeewolde.Name:                Zeewolde,
	Schoonebeek.Name:             Schoonebeek,
	BerkelEnschot.Name:           BerkelEnschot,
	Veldhoven.Name:               Veldhoven,
	Vught.Name:                   Vught,
	Dreumel.Name:                 Dreumel,
	Stroe.Name:                   Stroe,
	Laren.Name:                   Laren,
	Montfoort.Name:               Montfoort,
	Rijswijk.Name:                Rijswijk,
	Maasland.Name:                Maasland,
	Monster.Name:                 Monster,
	Wassenaar.Name:               Wassenaar,
	DeLier.Name:                  DeLier,
	Wateringen.Name:              Wateringen,
	Leidschendam.Name:            Leidschendam,
	Gravenzande.Name:             Gravenzande,
	Pijnacker.Name:               Pijnacker,
	Oosterhout.Name:              Oosterhout,
	Bleiswijk.Name:               Bleiswijk,
	HoekVanHolland.Name:          HoekVanHolland,
	Emmen.Name:                   Emmen,
	Nuenen.Name:                  Nuenen,
	Ulrum.Name:                   Ulrum,
	Zoutkamp.Name:                Zoutkamp,
	VelsenNoord.Name:             VelsenNoord,
	Maassluis.Name:               Maassluis,
	Moerkapelle.Name:             Moerkapelle,
	Rhoon.Name:                   Rhoon,
	Dongen.Name:                  Dongen,
	Nijmegen.Name:                Nijmegen,
	Goirle.Name:                  Goirle,
	Rosmalen.Name:                Rosmalen,
	Hooglanderveen.Name:          Hooglanderveen,
	Gorredijk.Name:               Gorredijk,
	Haren.Name:                   Haren,
	Leusden.Name:                 Leusden,
	Westervoort.Name:             Westervoort,
	Bergschenhoek.Name:           Bergschenhoek,
	Veghel.Name:                  Veghel,
	Beilen.Name:                  Beilen,
	Poeldijk.Name:                Poeldijk,
	DenHoorn.Name:                DenHoorn,
	Bloemendaal.Name:             Bloemendaal,
	Ridderkerk.Name:              Ridderkerk,
	Schijndel.Name:               Schijndel,
	Noordeloos.Name:              Noordeloos,
	BovenLeeuwen.Name:            BovenLeeuwen,
	KerkAvezaath.Name:            KerkAvezaath,
	Vogelenzang.Name:             Vogelenzang,
	WeheDenHoorn.Name:            WeheDenHoorn,
	Schipluiden.Name:             Schipluiden,
	Raalte.Name:                  Raalte,
	Brielle.Name:                 Brielle,
	Weteringbrug.Name:            Weteringbrug,
	Brandwijk.Name:               Brandwijk,
	Bennebroek.Name:              Bennebroek,
	BergenOpZoom.Name:            BergenOpZoom,
	HeiEnBoeicop.Name:            HeiEnBoeicop,
	TenPost.Name:                 TenPost,
	Bruchem.Name:                 Bruchem,
	GrootAmmers.Name:             GrootAmmers,
	Nieuwland.Name:               Nieuwland,
	Aalst.Name:                   Aalst,
	Ochten.Name:                  Ochten,
	Werkhoven.Name:               Werkhoven,
	Voorthuizen.Name:             Voorthuizen,
	Uithuizermeeden.Name:         Uithuizermeeden,
	Bedum.Name:                   Bedum,
	Kraggenburg.Name:             Kraggenburg,
	Honselersdijk.Name:           Honselersdijk,
	Baflo.Name:                   Baflo,
	Rhenoy.Name:                  Rhenoy,
	Dodewaard.Name:               Dodewaard,
	BerkelEnRodenrijs.Name:       BerkelEnRodenrijs,
	Holten.Name:                  Holten,
	Rijssen.Name:                 Rijssen,
	Dussen.Name:                  Dussen,
	Didam.Name:                   Didam,
	Duiven.Name:                  Duiven,
	Duivendrecht.Name:            Duivendrecht,
	Zoelen.Name:                  Zoelen,
	Ameide.Name:                  Ameide,
	Kwintsheul.Name:              Kwintsheul,
	Nootdorp.Name:                Nootdorp,
	Delfgauw.Name:                Delfgauw,
	HoefEnHaag.Name:              HoefEnHaag,
	Luttelgeest.Name:             Luttelgeest,
	SantpoortZuid.Name:           SantpoortZuid,
}

// City defines a city where a housing corporation operates or when an house offer lies
type City struct {
	CreatedAt         time.Time           `pg:"default:now()" json:"-"`
	Name              string              `pg:",pk" json:"name"`
	Latitude          float64             `json:"latitude,omitempty"`
	Longitude         float64             `json:"longitude,omitempty"`
	District          []string            `pg:"-" json:"district,omitempty"`
	SuggestedDistrict map[string][]string `pg:"-" json:"suggested_district,omitempty"`
}

// Merge cities that are supposed to be the same but that housing corporation name differently
func (c *City) Merge() City {
	// TODO try equal fold for every member of the list

	switch {
	case strings.Contains(c.Name, "Amsterdam"):
		return Amsterdam
	case strings.Contains(c.Name, "Hengelo"):
		return Hengelo
	case strings.Contains(c.Name, "Winterswijk"):
		return Winterswijk
	case strings.EqualFold(c.Name, "s-Heerenberg"):
		return Heerenberg
	case strings.Contains(c.Name, "IJsselstein"):
		return IJsselstein
	case strings.Contains(c.Name, "Hertogenbosch"):
		return Hertogenbosch
	case strings.Contains(c.Name, "Gravenhage"):
		return DenHaag
	case strings.EqualFold(c.Name, "Zoetermeer"):
		return Zoetermeer
	case strings.Contains(c.Name, "Bodegraven"):
		return Bodegraven
	case strings.Contains(c.Name, "Graveland"):
		return Graveland
	case strings.Contains(c.Name, "Elst"):
		return Elst
	case strings.Contains(c.Name, "Nieuwerkerk a/d"):
		return NieuwerkerkAanDenIJssel
	case strings.Contains(c.Name, "Rijswijk"):
		return Rijswijk
	case strings.Contains(c.Name, "Gravenzande"):
		return Gravenzande
	case strings.EqualFold(c.Name, "Haren Gn"):
		return Haren
	}

	return *c
}

// SuggestedCityDistrict permit to get city suggested districts
func SuggestedCityDistrict(name string) map[string][]string {
	city, ok := CityTable[name]
	if !ok || len(city.SuggestedDistrict) == 0 {
		return nil
	}

	return city.SuggestedDistrict
}
