package city

import "github.com/woningfinder/woningfinder/internal/corporation"

// https://nl.wikipedia.org/wiki/Wijken_en_buurten_in_Enschede
var Enschede = corporation.City{
	Name: "Enschede",
	District: []string{
		"City (Oude Markt)",
		"Lasonder, Zeggelt",
		"De Laares",
		"De Bothoven",
		"Hogeland",
		"Getfert",
		"Veldkamp",
		"Stadsweide",
		"Boddenkamp",
		"Velve-Lindenhof",
		"Wooldrik",
		"Varvik-Diekman",
		"Sleutelkamp",
		"De Leuriks",
		"Cromhoffsbleek",
		"Boswinkel",
		"Pathmos",
		"Stevenfenne",
		"Stadsveld",
		"Elferink-Heuwkamp",
		"'t Zwering",
		"Ruwenbos",
		"Tubantia-Toekomst",
		"Twekkelerveld",
		"Walhof-Roessingh",
		"Bolhaar",
		"Roombeek-Roomveldje",
		"Mekkelholt",
		"Deppenbroek",
		"Voortman-Amelink",
		"Drienerveld-U.T.",
		"Schreurserve",
		"Ribbelt",
		"Stokhorst",
		"Stroinkslanden",
		"Helmerhoek",
		"Glanerveld (Glanerbrug)",
		"Bentveld-Bultserve (Glanerbrug)",
		"Schipholt-Glanermaten (Glanerbrug)",
		"Eekmaat (Glanerbrug)",
		"Oikos (Glanerbrug)",
		"Dolphia (Glanerbrug)",
	},
}
