package city

// https://nl.wikipedia.org/wiki/Wijken_en_buurten_in_Utrecht
var Utrecht = City{
	Name: "Utrecht",
	District: map[string][]string{
		"West": {
			"Welgelegen",
			"Den Hommel",
			"Oog in Al",
			"Halve Maan",
			"Lombok-Oost",
			"Leidseweg en omgeving",
			"Lombok-West",
			"Laan van Nieuw Guinea-Spinozaplantsoen",
			"Nieuw Engeland",
			"Schepenbuurt",
			"Lage weide",
		},
		"Noordwest": {
			"Pijlsweerd-Zuid",
			"Pijlsweerd-Noord",
			"Ondiep",
			"Tweede Daalsebuurt",
			"Egelantierstraat-Mariëndaalstraat",
			"Geuzenwijk",
			"De Driehoek",
			"Julianapark",
			"Elinkwijk",
			"Prins Bernhardplein",
			"Schaakbuurt",
			"Queeckhovenplein",
			"Zuilen-Noord",
			"Loevenhoutsedijk",
		},
		"Overvecht": {
			"Taag- en Rubicondreef",
			"Zamenhofdreef",
			"Wolga- en Donaudreef",
			"Neckardreef",
			"Amazone- en Nicaraguadreef",
			"Zambesidreef",
			"Tigris- en Bostondreef",
			"Bedrijvengebied",
			"Poldergebied Overvecht",
		},
		"Noordoost": {
			"Vogelenbuurt",
			"Lauwerecht",
			"Staatsliedenbuurt",
			"Tuinwijk-West",
			"Tuinwijk-Oost",
			"Tuindorp en Van Lieflandlaan-West",
			"Tuindorp-Oost",
			"Huizingalaan K. Doormanlaan",
			"Zeeheldenbuurt",
			"Wittevrouwen",
			"Voordorp",
		},
		"Oost": {
			"Buiten Wittevrouwen",
			"Tolsteegsingel",
			"Sterrenwijk",
			"Watervogelbuurt",
			"Lodewijk Napoleonplantsoen",
			"Rubenslaan",
			"Schildersbuurt",
			"Abstede",
			"Oudwijk",
			"Wilhelminapark",
			"De Uithof",
			"Rijnsweerd",
			"Galgenwaard en Kromhoutkazerne",
			"Maarschalkerweerd en Mereveld",
		},
		"Binnenstad": {
			"Wijk C",
			"Breedstraat en Plompetorengracht",
			"Lange Elisabethstraat Mariaplaats",
			"Neude Janskerkhof en Domplein",
			"Nobelstraat",
			"Springweg",
			"Lange Nieuwstraat",
			"Nieuwegracht-Oost",
			"Bleekstraat",
			"Hooch Boulandt Moreelsepark",
			"Hoog-Catharijne CS en Leidseveer",
		},
		"Zuid": {
			"Lunetten-Noord",
			"Lunetten-Zuid",
			"Bokkenbuurt",
			"Tolsteeg en Rotsoord",
			"Oud Hoograven",
			"Nieuw Hoograven",
		},
		"Zuidwest": {
			"Dichterswijk",
			"Rivierenwijk",
			"Bedrijvengebied Kanaleneiland",
			"Transwijk-Zuid",
			"Transwijk-Noord",
			"Kanaleneiland-Zuid",
			"Kanaleneiland-Noord",
		},
		"Leidsche Rijn": {
			"Papendorp",
			"Bedrijventerrein De Wetering",
			"Terwijde",
			"Parkwijk, 't Zand",
			"Hogeweide",
			"Langerak",
			"Strijkviertel",
		},
		"Vleuten-De Meern ": nil,
	},
}
