package city

import "github.com/woningfinder/woningfinder/internal/domain/entity"

var Zwolle = entity.City{
	Name: "Zwolle",
	District: []entity.CityDistrict{
		{Name: "Binnenstad"},
		{Name: "Dieze-Centrum"},
		{Name: "Milligen"},
		{Name: "Frankhuis"},
		{Name: "Schoonhorst"},
		{Name: "Assendorp"},
		{Name: "Berkum"},
		{Name: "Aalanden"},
		{Name: "Ittersumerlanden"},
		{Name: "Oldenelerbroek"},
		{Name: "Gerenbroek"},
		{Name: "Hogenkamp"},
		{Name: "Gerenlanden"},
		{Name: "Wipstrik"},
		{Name: "Schellerlanden"},
		{Name: "Holtenbroek"},
		{Name: "Westenholte"},
		{Name: "Oldenelerlanden"},
		{Name: "Ittersumerbroek"},
		{Name: "Pierik"},
		{Name: "Bollebieste"},
		{Name: "Schellerbroek"},
		{Name: "Oud Ittersum"},
		{Name: "Kamperpoort"},
		{Name: "Veerallee"},
		{Name: "Stationsbuurt"},
		{Name: "Schellerhoek"},
		{Name: "Oud Schelle"},
		{Name: "Hanzeland"},
		{Name: "Het Noorden"},
		{Name: "Indische Buurt"},
		{Name: "Bagijneweide"},
		{Name: "Geren"},
		{Name: "Wezenlanden"},
		{Name: "Meppelerstraatweg"},
	},
}
