on: [push]
name: Test & Build
jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    env:
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test $(go list ./... | grep -v /internal/corporation/connector) # ignore connectors

      - name: Build
        run: go build ./cmd/...
