on:
  schedule:
    - cron: "0 0 * * *"
name: Verify ikwilhuren.nu connector
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test ./internal/corporation/connector/ikwilhuren/...
