on:
  schedule:
    - cron: "0 0 * * *"
name: Verify De Woonplaats connector
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18"]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test ./internal/corporation/connector/dewoonplaats/...
