on:
  schedule:
    - cron: '0 0 * * *'
name: Verify connector
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
    strategy:
      matrix:
        go: [ '1.16' ]
    steps:
    
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Verify De Woonplaats
      run: go test ./internal/corporation/connector/dewoonplaats/...

    - name: Verify Domijn
      run: go test ./internal/corporation/connector/domijn/...

    - name: Verify Itris
      run: go test ./internal/corporation/connector/itris/...